# tool: "Knighter"
# vulnerability: "UBI"
# vulnerability_info_file: "../data/in_house/c/vulnerabilities.json"
# projects_dir: "../data/projects/"
# log: "../logs/"
# results: "../results/knighter/"

# tool: "inferroi"
# vulnerability: "CWE-022"
# vulnerability_info_file: "../data/in_house/java/vulnerabilities.json"
# projects_dir: "/data/lifengjie/sec/src/dependencies/iris/data/cwe-bench-java/project-sources/"
# log: "../logs/"
# results: "../results/inferroi/"

tool: "repoaudit"
vulnerability: "CWE-401"
vulnerability_info_file: "../data/in_house/c/reposvul_vulnerabilities.json"
projects_dir: "/data/jiangjiajun/LLM4Security/data/projects"
log: "../logs/"
results: "../results/repoaudit/"