# tool: "Knighter"
# vulnerability: "UBI"
# vulnerability_info_file: "../data/in_house/c/vulnerabilities.json"
# projects_dir: "../data/projects/"
# log: "../logs/"
# results: "../results/knighter/"

# tool: "inferroi"
# vulnerability: "jleaks"
# vulnerability_info_file: "../data/in_house/java/jleaks_vulnerabilities.json"
# projects_dir: "/data/jiangjiajun/LLM4Security/data/in_house/java/projects"
# log: "../logs/"
# results: "../results/inferroi/"

tool: "repoaudit"
vulnerability: "CWE-401"
vulnerability_info_file: "../data/in_house/c/reposvul_vulnerabilities.json"
projects_dir: "/data/jiangjiajun/LLM4Security/data/projects"
log: "../logs/repoaudit/"
results: "../results/repoaudit/"

# tool: "iris"
# vulnerability: "CWE-022"
# vulnerability_info_file: "./dependencies/iris/data/cwe-bench-java/data/project_info.csv"
# projects_dir: ""
# log: "../logs/"
# results: "../results/iris/"

# tool: "llmdfa"
# vulnerability: "CWE-079"
# vulnerability_info_file: "./dependencies/iris/data/cwe-bench-java/data/project_info.csv"
# vulnerability_fl_file: "./dependencies/iris/data/cwe-bench-java/data/fix_info.csv"
# projects_dir: ""
# log: "../logs/llmdfa/"
# results: "../results/llmdfa/"

# tool: "llmsan"
# vulnerability: "CWE-079"
# vulnerability_info_file: "./dependencies/iris/data/cwe-bench-java/data/project_info.csv"
# vulnerability_fl_file: "./dependencies/iris/data/cwe-bench-java/data/fix_info.csv"
# projects_dir: ""
# log: "../logs/llmsan/"
# results: "../results/llmsan/"

# tool: "codeql"
# vulnerability: "CWE-416"
# vulnerability_info_file: "../data/in_house/c/reposvul_vulnerabilities.json"
# projects_dir: "/data/jiangjiajun/LLM4Security/data/projects"
# log: "../logs/codeql/"
# results: "../results/codeql/"

# tool: "semgrep"
# vulnerability: "CWE-078"
# vulnerability_info_file: "../data/in_house/java/project_info.csv"
# projects_dir: "/data/jiangjiajun/LLM4Security/src/dependencies/iris/data/cwe-bench-java/project-sources"
# log: "../logs/semgrep/"
# results: "../results/semgrep/"