# tool: "Knighter"
# vulnerability: "UBI"
# vulnerability_info_file: "../data/in_house/c/vulnerabilities.json"
# projects_dir: "../data/projects/"
# log: "../logs/"
# results: "../results/knighter/"

# tool: "inferroi"
# vulnerability: "jleaks"
# vulnerability_info_file: "../data/in_house/java/jleaks_vulnerabilities.json"
# projects_dir: "/data/jiangjiajun/LLM4Security/data/in_house/java/projects"
# log: "../logs/"
# results: "../results/inferroi/"

tool: "repoaudit"
vulnerability: "CWE-401"
vulnerability_info_file: "../data/in_house/c/reposvul_vulnerabilities.json"
projects_dir: "/data/jiangjiajun/LLM4Security/data/projects"
log: "../logs/"
results: "../results/repoaudit/"